import { test,expect,type Page } from "@playwright/test";
async function login(page:Page,email="care@example.test"){
  await page.goto("/login");await page.getByLabel("Correo electrónico",{exact:true}).first().fill(email);
  await page.getByLabel("Contraseña",{exact:true}).fill("mi jardín tiene hojas");
  await page.getByRole("button",{name:"Ingresar a mi jardín"}).click();await expect(page).toHaveURL(/\/plants$/);
}
test("configura agenda, registra riego, pausa y protege datos entre cuentas",async({page,browser})=>{
  await login(page);
  await page.getByRole("heading",{name:"Monstera de Sol",exact:true}).click();
  await page.getByRole("link",{name:"Riego y cuidados",exact:true}).click();
  await page.getByLabel("Intervalo base (días)").fill("7");await page.getByLabel("Modo de la agenda").selectOption("manual");
  await page.getByLabel("Fecha de inicio de seguimiento").fill("2026-01-01");
  await page.getByRole("button",{name:"Guardar agenda",exact:true}).click();
  await expect(page.getByText("8 de enero de 2026",{exact:true})).toBeVisible();
  await page.getByRole("link",{name:"Ver agenda y configurar clima"}).click();
  await page.getByText("Configurar ubicación y zona horaria",{exact:true}).click();
  await page.getByRole("button",{name:"Usar Buenos Aires",exact:true}).click();
  await page.getByRole("button",{name:"Guardar ubicación",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Ubicación guardada");
  await expect(page.getByRole("button",{name:"Actualizar clima",exact:true})).toBeDisabled();
  await page.getByText("Configurar ubicación y zona horaria",{exact:true}).click();
  await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();window.scrollTo(0,0);});
  await page.screenshot({path:"test-results/phase5-agenda-desktop.png",fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:"test-results/phase5-agenda-mobile.png",fullPage:true});
  await page.getByLabel("Confirmo que regué esta planta hoy").check();
  await page.getByRole("button",{name:"Registrar riego de hoy",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Riego anotado");
  await expect(page.getByText("Último riego en el diario:",{exact:false})).toBeVisible();
  await page.getByRole("link",{name:"Ver diario",exact:false}).click();
  await expect(page.getByText("Riego registrado desde la agenda.",{exact:true})).toBeVisible();
  await page.getByRole("link",{name:"Riego y cuidados",exact:true}).click();
  await page.getByLabel("Estado de la agenda").selectOption("no");
  await page.getByRole("button",{name:"Guardar agenda",exact:true}).click();
  await expect(page.getByText("PAUSADA",{exact:true})).toBeVisible();
  await expect(page.getByRole("button",{name:"Registrar riego de hoy",exact:true})).toHaveCount(0);
  const url=page.url();
  const context=await browser.newContext();const stranger=await context.newPage();await login(stranger,"other@example.test");
  await stranger.goto(url);await expect(stranger.getByRole("heading",{name:"Por acá todavía no crece nada."})).toBeVisible();
  await stranger.goto("/plants/care");await expect(stranger.getByRole("heading",{name:"Monstera de Sol",exact:true})).toHaveCount(0);
  await context.close();
});
test("calculadora interactiva usa especie, estado y volumen sin modificar ficha",async({page})=>{
  await login(page);await page.goto("/plants/b7157311-ace0-4a59-9200-000000000040/calculator");
  await expect(page.getByLabel("Grupo de planta")).toHaveValue("foliage");
  await page.getByLabel("Estado actual").selectOption("crowded");
  await expect(page.getByText("17.5 cm",{exact:true})).toBeVisible();
  await page.getByLabel("Diámetro interior de la boca (cm)").fill("20");
  await page.getByLabel("Diámetro interior de la base (cm)").fill("20");
  await page.getByLabel("Altura interior (cm)").fill("20");
  await page.getByLabel("Espacio libre hasta el borde (cm)").fill("0");
  await page.getByLabel("Diámetro del cepellón (cm)").fill("10");
  await page.getByLabel("Altura del cepellón (cm)").fill("10");
  await expect(page.getByText("6,05 L",{exact:true})).toBeVisible();
  await page.getByLabel("Diámetro del cepellón (cm)").fill("25");
  await expect(page.getByRole("status")).toContainText("no cabe");
  await page.getByLabel("Diámetro del cepellón (cm)").fill("10");
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();window.scrollTo(0,0);});
  await page.screenshot({path:"test-results/phase5-calculator-mobile.png",fullPage:true});
  await page.getByRole("link",{name:"Volver a Monstera de Sol"}).click();
  await expect(page.getByText("Ø 15 cm · 15 cm de alto",{exact:true})).toBeVisible();
});
