import { test, expect, type Page } from "@playwright/test";
import sharp from "sharp";

async function login(page: Page) {
  await page.goto("/login");
  await page.getByLabel("Correo electrónico", { exact: true }).first().fill("crud@example.test");
  await page.getByLabel("Contraseña", { exact: true }).fill("mi jardín tiene hojas");
  await page.getByRole("button", { name: "Ingresar a mi jardín" }).click();
  await expect(page).toHaveURL(/\/plants$/);
}
test("CRUD, diario con foto privada, archivo, restauración y limpieza", async ({ page, browser }) => {
  await login(page);
  await page.getByRole("link", { name: "Agregar planta", exact: true }).click();
  await page.getByLabel("Nombre de tu planta").fill("Helecho de Martina");
  await page.getByLabel("Nombre de especie anotado").fill("Helecho");
  await page.getByLabel("Ubicación", { exact: true }).fill("Biblioteca");
  await page.getByLabel("Diámetro de maceta").fill("18");
  await page.getByRole("button", { name: "Agregar planta", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Helecho de Martina", exact: true })).toBeVisible();
  const plantUrl = page.url();
  await page.getByRole("link", { name: "Editar ficha" }).click();
  await page.getByLabel("Ubicación", { exact: true }).fill("Estudio");
  await page.getByRole("button", { name: "Guardar cambios" }).click();
  await expect(page.getByText("Estudio", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Nuevo registro" }).click();
  await page.getByLabel("Fecha", { exact: false }).fill("2026-01-15");
  await page.getByLabel("Tipo de registro").selectOption("watering");
  await page.getByLabel("¿Qué observaste?").fill("Una hoja nueva después del riego.");
  await page.getByLabel("Agua utilizada").fill("150");
  await page.getByLabel("Altura de la planta").fill("24.5");
  const photo = await sharp({ create: { width: 700, height: 480, channels: 3, background: "#678a4e" } }).png().toBuffer();
  await page.getByLabel("Adjuntar foto").setInputFiles({ name: "hoja.png", mimeType: "image/png", buffer: photo });
  await page.getByRole("button", { name: "Agregar al diario" }).click();
  await expect(page.getByText("Una hoja nueva después del riego.", { exact: true })).toBeVisible();
  const image = page.getByRole("img", { name: /Helecho de Martina/ });
  await expect(image).toBeVisible();
  await expect.poll(() => image.evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0);
  const mediaUrl = await image.getAttribute("src");
  const privateContext = await browser.newContext();
  expect((await privateContext.request.get(`http://127.0.0.1:3100${mediaUrl}`)).status()).toBe(401);
  const stranger = await privateContext.newPage();
  await stranger.goto("/login");
  await stranger.getByLabel("Correo electrónico", { exact: true }).first().fill("other@example.test");
  await stranger.getByLabel("Contraseña", { exact: true }).fill("mi jardín tiene hojas");
  await stranger.getByRole("button", { name: "Ingresar a mi jardín" }).click();
  await expect(stranger).toHaveURL(/\/plants$/);
  expect((await privateContext.request.get(`http://127.0.0.1:3100${mediaUrl}`)).status()).toBe(404);
  await stranger.goto(plantUrl);
  await expect(stranger.getByRole("heading", { name: "Por acá todavía no crece nada." })).toBeVisible();
  await privateContext.close();
  await page.evaluate(() => { (document.activeElement as HTMLElement)?.blur(); window.scrollTo(0, 0); });
  await page.screenshot({ path: "test-results/phase3-diary-desktop.png", fullPage: true, caret: "initial" });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "test-results/phase3-diary-mobile.png", fullPage: true, caret: "initial" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole("link", { name: "Editar registro" }).click();
  await page.getByLabel("¿Qué observaste?").fill("El sustrato conservó la humedad.");
  await page.getByRole("button", { name: "Guardar entrada" }).click();
  await expect(page.getByText("El sustrato conservó la humedad.", { exact: true })).toBeVisible();
  await page.getByText("Administrar esta planta", { exact: true }).click();
  await page.getByRole("button", { name: "Archivar planta", exact: true }).click();
  await expect(page.getByText("PLANTA ARCHIVADA", { exact: true })).toBeVisible();
  await expect(page.getByRole("link", { name: "Nuevo registro" })).toHaveCount(0);
  await page.goto("/plants?archived=1");
  await page.getByRole("link", { name: /Helecho de Martina/ }).click();
  await page.getByText("Administrar esta planta", { exact: true }).click();
  await page.getByRole("button", { name: "Restaurar planta" }).click();
  await expect(page.getByRole("link", { name: "Nuevo registro" })).toBeVisible();
  await page.getByRole("link", { name: "Editar registro" }).click();
  await page.getByText("Eliminar esta entrada", { exact: true }).click();
  await page.getByLabel("Escribí ELIMINAR para confirmar").fill("ELIMINAR");
  await page.getByRole("button", { name: "Eliminar entrada definitivamente" }).click();
  await expect(page.getByRole("heading", { name: "Su historia empieza con una mirada" })).toBeVisible();
  expect((await page.request.get(mediaUrl!)).status()).toBe(404);
  await page.getByText("Administrar esta planta", { exact: true }).click();
  await page.getByLabel("Escribí «Helecho de Martina» para confirmar").fill("Helecho de Martina");
  await page.getByRole("button", { name: "Eliminar planta definitivamente" }).click();
  await expect(page).toHaveURL(/\/plants$/);
  await expect(page.getByRole("heading", { name: "Todo empieza con una primera planta" })).toBeVisible();
});

test("rechaza archivos falsos, conserva los datos y detecta edición simultánea", async ({ page, context }) => {
  await login(page);
  await page.goto("/plants/new");
  await page.getByLabel("Nombre de tu planta").fill("Planta de validación");
  await page.getByRole("button", { name: "Agregar planta", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Planta de validación", exact: true })).toBeVisible();
  const plantUrl = page.url();
  await page.goto(`${plantUrl}/edit`);
  const second = await context.newPage();
  await second.goto(`${plantUrl}/edit`);
  await page.getByLabel("Ubicación", { exact: true }).fill("Ventana");
  await page.getByRole("button", { name: "Guardar cambios" }).click();
  await expect(page.getByText("Ventana", { exact: true })).toBeVisible();
  await second.getByLabel("Ubicación", { exact: true }).fill("Patio");
  await second.getByRole("button", { name: "Guardar cambios" }).click();
  await expect(second.getByRole("main").getByRole("alert")).toContainText("otra ventana");
  await second.close();
  await page.goto(`${plantUrl}/journal/new`);
  await page.getByLabel("¿Qué observaste?").fill("Esta nota debe conservarse tras el error.");
  await page.getByLabel("Adjuntar foto").setInputFiles({ name: "falsa.jpg", mimeType: "image/jpeg", buffer: Buffer.from("esto no es una foto") });
  await page.getByRole("button", { name: "Agregar al diario" }).click();
  await expect(page.getByRole("main").getByRole("alert")).toContainText("No pudimos leer");
  await expect(page.getByLabel("¿Qué observaste?")).toHaveValue("Esta nota debe conservarse tras el error.");
  await page.getByLabel("Adjuntar foto").setInputFiles([]);
  await page.getByRole("button", { name: "Agregar al diario" }).click();
  await expect(page.getByText("Esta nota debe conservarse tras el error.", { exact: true })).toBeVisible();
});
