"use client";
import { useState } from "react";
import { calculatePot, groups, speciesGroup, recommendedDiameter } from "./calculator";

export function PotCalculator({ species, diameter, height, drainage }: { species: string | null; diameter: number | null; height: number | null; drainage: boolean | null }) {
  const [group,setGroup]=useState<keyof typeof groups>(speciesGroup(species));
  const [state,setState]=useState<"comfortable"|"crowded"|"stressed">("comfortable");
  const [values,setValues]=useState<Record<string,string>>({ currentDiameter: String(diameter ?? 15), top: String(diameter ?? 15), bottom: String(diameter ?? 15), height: String(height ?? 15), headroom:"2", rootDiameter:"0", rootHeight:"0" });
  let result: ReturnType<typeof calculatePot> | null=null; let error="";
  try {
    if (Object.values(values).some((v) => v.trim()==="")) throw new Error("Completá todas las medidas para calcular.");
    result=calculatePot({ currentDiameter:Number(values.currentDiameter), top:Number(values.top), bottom:Number(values.bottom), height:Number(values.height), headroom:Number(values.headroom), rootDiameter:Number(values.rootDiameter), rootHeight:Number(values.rootHeight), group,state });
  } catch (issue) { error=issue instanceof Error && !issue.message.startsWith("[") ? issue.message : "Usá medidas válidas: maceta de 3 a 100 cm, base no mayor que la boca y espacio superior menor que la altura."; }
  const field=(name:string,label:string,min:number,max:number) => <div className="field" key={name}><label htmlFor={name}>{label}</label><input id={name} type="number" min={min} max={max} step="0.1" value={values[name]} onChange={(e)=>setValues({...values,[name]:e.target.value})} /></div>;
  const format=(n:number)=>n.toLocaleString("es-AR",{minimumFractionDigits:2,maximumFractionDigits:2});
  return <div className="pot-calculator"><section className="editor-section"><h2>La planta y sus raíces</h2><p>Especie anotada: <strong>{species ?? "Sin identificar"}</strong>. Confirmá el grupo: la sugerencia por nombre puede no corresponder a tu ejemplar.</p>
    <div className="form-grid"><div className="field full-width"><label htmlFor="group">Grupo de planta</label><select id="group" value={group} onChange={(e)=>setGroup(e.target.value as keyof typeof groups)}>{Object.entries(groups).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>
    {field("currentDiameter","Diámetro de la maceta actual (cm)",3,100)}<div className="field"><label htmlFor="root-state">Estado actual</label><select id="root-state" value={state} onChange={(e)=>setState(e.target.value as typeof state)}><option value="comfortable">Raíces con espacio / crecimiento normal</option><option value="crowded">Raíces apretadas, ocupan la maceta</option><option value="stressed">Planta debilitada o raíces dañadas</option></select></div></div>
    {Number(values.currentDiameter)>=3 && Number(values.currentDiameter)<=100 && <p className="pot-suggestion">Diámetro orientativo: <strong>{recommendedDiameter(Number(values.currentDiameter),state)} cm</strong>. {state==="crowded" ? "Un aumento moderado evita un exceso de sustrato húmedo." : state==="stressed" ? "Revisá la causa del deterioro antes de trasplantar; aumentar la maceta no resuelve por sí solo el problema." : "No es necesario aumentar la maceta solo por el paso del tiempo."}</p>}
    <p className="field-hint">Elegí una maceta con orificios de drenaje.{drainage===false ? " Tu ficha indica que la actual no tiene drenaje." : ""} Estas mezclas son puntos de partida por grupo; requieren adaptación a la especie, al ambiente y a los materiales disponibles.</p>
  </section><section className="editor-section"><h2>Cuánto sustrato preparar</h2><p>Medí el interior de la maceta destino. Para una maceta cilíndrica, usá el mismo diámetro en la boca y en la base. Para una maceta vacía, dejá ambas medidas del cepellón en cero; para un trasplante, medí el bloque de raíces y tierra que vas a conservar.</p><div className="form-grid">
    {field("top","Diámetro interior de la boca (cm)",3,120)}{field("bottom","Diámetro interior de la base (cm)",1,120)}{field("height","Altura interior (cm)",3,100)}{field("headroom","Espacio libre hasta el borde (cm)",0,10)}{field("rootDiameter","Diámetro del cepellón (cm)",0,100)}{field("rootHeight","Altura del cepellón (cm)",0,100)}
    </div><div aria-live="polite" aria-atomic="true">{error ? <p role="status" className="error-box">{error}</p> : result && <section className="pot-result"><h3>Tu mezcla estimada</h3><p className="pot-liters"><strong>{format(result.prepare)} L</strong> para preparar</p><p>Capacidad útil: {format(result.capacity)} L · Cepellón: {format(result.rootLiters)} L · Espacio a completar: {format(result.liters)} L.</p><p>Incluye un 10 % extra para pequeñas pérdidas y asentamiento.</p><ul>{result.components.map((c)=><li key={c.name}><span>{c.name} ({c.percent} %)</span><strong>{format(c.liters)} L</strong></li>)}</ul><p className="field-hint">Volumen aproximado de un tronco de cono menos un cepellón cilíndrico. No representa una dosis de fertilizante ni modifica tu ficha.</p></section>}</div>
  </section></div>;
}
