"use client";
import { useActionState, useState } from "react";
import { saveLocation, updateWeather, saveSchedule, recordWatering } from "./actions";
import { initialState, type FormState } from "@/features/plants/validation";
import type { AgendaEntry } from "./schemas";

function Feedback({ state }: { state: FormState }) { return state.message ? <p role={state.status==="error" ? "alert" : "status"} className={state.status==="error" ? "error-box" : "success-box"}>{state.message}</p> : null; }
export function LocationForm({ latitude,longitude,timezone }: { latitude:number|null; longitude:number|null; timezone:string }) {
  const [state,action,pending]=useActionState(saveLocation,initialState);
  const [lat,setLat]=useState(latitude?.toString()??""); const [lon,setLon]=useState(longitude?.toString()??""); const [zone,setZone]=useState(timezone);
  return <form action={action} className="editor-form" aria-busy={pending}><Feedback state={state}/><fieldset disabled={pending}><section className="editor-section"><h2>Tu ubicación para el clima</h2><p>Usá coordenadas aproximadas de tu ciudad. Se redondean a dos decimales y se envían a OpenWeather solo al consultar el clima. Para quitar la ubicación, dejá ambas coordenadas vacías.</p>
    <div className="form-grid"><div className="field"><label htmlFor="latitude">Latitud</label><input id="latitude" name="latitude" type="number" min="-90" max="90" step="any" value={lat} onChange={(e)=>setLat(e.target.value)}/></div><div className="field"><label htmlFor="longitude">Longitud</label><input id="longitude" name="longitude" type="number" min="-180" max="180" step="any" value={lon} onChange={(e)=>setLon(e.target.value)}/></div><div className="field full-width"><label htmlFor="timezone">Zona horaria</label><input id="timezone" name="timezone" required maxLength={100} value={zone} onChange={(e)=>setZone(e.target.value)}/><span className="field-hint">Ejemplo: America/Argentina/Buenos_Aires o Europe/Madrid. No es un número GMT.</span></div></div>
    <div className="care-actions"><button className="button button-secondary" type="button" onClick={()=>{setLat("-34.60");setLon("-58.38");setZone("America/Argentina/Buenos_Aires");}}>Usar Buenos Aires</button><button className="button button-primary" type="submit">{pending ? "Guardando…" : "Guardar ubicación"}</button></div>
  </section></fieldset></form>;
}
export function WeatherButton({ configured }: { configured:boolean }) {
  const [state,action,pending]=useActionState(updateWeather,initialState);
  return <form action={action} aria-busy={pending}><Feedback state={state}/><button type="submit" className="button button-secondary" disabled={!configured||pending}>{pending ? "Consultando clima…" : "Actualizar clima"}</button>{!configured && <p className="field-hint">El clima todavía no está configurado. La agenda puede ajustar por estación si guardaste la ubicación.</p>}</form>;
}
export function ScheduleForm({ plant,schedule,speciesBase,today }: { plant:string; schedule:AgendaEntry|null; speciesBase:number|null; today:string }) {
  const [state,action,pending]=useActionState(saveSchedule,initialState);
  return <form action={action} className="editor-form" aria-busy={pending}><input name="plant" type="hidden" value={plant}/><input name="version" type="hidden" value={schedule?.version ?? ""}/><Feedback state={state}/><fieldset disabled={pending}><section className="editor-section"><h2>Configurar revisiones de riego</h2><p>{speciesBase ? `El catálogo revisado sugiere una base de ${speciesBase} días. Ajustala según tu experiencia.` : "Elegí el intervalo base según la especie y tus observaciones. No usamos un intervalo universal para todas las plantas."}</p><div className="form-grid"><div className="field"><label htmlFor="base">Intervalo base (días)</label><input id="base" name="base" type="number" min="1" max="365" required defaultValue={schedule?.base_interval_days ?? speciesBase ?? ""}/></div><div className="field"><label htmlFor="mode">Modo de la agenda</label><select id="mode" name="mode" defaultValue={schedule?.mode ?? "adaptive"}><option value="adaptive">Adaptar por estación y clima</option><option value="manual">Mantener intervalo manual</option></select></div><div className="field"><label htmlFor="anchor">Fecha de inicio de seguimiento</label><input id="anchor" name="anchor" type="date" required max={today} defaultValue={schedule?.anchor_on ?? today}/><span className="field-hint">Se usa solo si no hay riegos en el diario; no crea un riego ficticio.</span></div><div className="field"><label htmlFor="enabled">Estado de la agenda</label><select id="enabled" name="enabled" defaultValue={schedule?.enabled===false ? "no" : "yes"}><option value="yes">Activa</option><option value="no">Pausada</option></select></div></div><button className="button button-primary" type="submit">{pending ? "Guardando…" : "Guardar agenda"}</button></section></fieldset></form>;
}
export function WateringButton({ id,plant }: { id:string; plant:string }) {
  const [state,action,pending]=useActionState(recordWatering,initialState);
  return <form action={action} className="watering-record" aria-busy={pending}><input name="id" type="hidden" value={id}/><input name="plant" type="hidden" value={plant}/><Feedback state={state}/>{state.status!=="success" && <><label><input type="checkbox" name="confirmation" required disabled={pending}/> Confirmo que regué esta planta hoy</label><button type="submit" className="button button-secondary" disabled={pending}>{pending ? "Anotando…" : "Registrar riego de hoy"}</button></>}</form>;
}
